apiVersion: v1
kind: Service
metadata:
  name: nextflix-app
  labels:
    app: nextflix-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: nextflix-app
  type: LoadBalancer
  #type: NodePort
